[package]
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2021"
name = "coordinator"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "coordinator"

[dependencies]
integrity = {path = "../integrity"}
serde = "1"
